# Site
title:              Project Incomplete
bio:                "Emmanuel Medina's Personal Blog, Portfolio, and page to mess around"
description:        "Emmanuel Medina's Personal Blog, Portfolio, and page to mess around"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "zaza.studio" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            zazathebassist
facebook:           default
instagram:          zazathebassist
github:             zazathebassist

# personal
location:           Southern California
email:              emedina94@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old, elements]
