# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:          Project Incomplete
name:           Emmanuel Medina
email: 
bio:            "Emmanuel Medina's Personal Blog, Portfolio, and page to mess around"
description:    "Emmanuel Medina's Personal Blog, Portfolio, and page to mess around"
locale:         en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zaza.studio" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: zazathebassist
github_username:  zazathebassist
# repository: "username/repo-name"


# Build settings
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"
include: ["_pages"]
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Personal Modifications

search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_label: "Contents"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

comments:
  provider: "disqus"
  disqus:
    shortname: "project-incomplete"

# Blog Styles

author:
  name     : "Emmanuel Medina"
  avatar   : "/images/zaza.jpg"
  bio      : "My awesome biography constrained to a sentence or two goes here."
  location : "Inland Empire, CA, USA" 
  links:
    - label:  "Project Incomplete"
      icon: "fas fa-fw fa-link"
      url: "https://zaza.studio"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/zazathebassist"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zazathebassist"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/zazathebassist"

paginate: 6
paginate_path: "/blog/page:num/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/zazathebassist"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zazathebassist"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/zazathebassist"

